version: '3.3'
services:
  post_db:
    image: kirillkotovsky/post:logging
    volumes:
      - post_db:/data/db
    networks:
      - back-network
      - front-network
      
  ui:
    build: ./ui
    image: kirillkotovsky/ui:logging
    ports:
      - ${UI_PORT}
    networks:
      - front-network
      - back-network
  post:
    image: ${USER_NAME}/post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    build: ./comment
    image: kirillkotovsky/comment:logging
    networks:
      - back-network
      - front-network 
volumes:
  post_db:

networks:
  back-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
